import path from "path";
import { fileURLToPath } from "url";
import { buildConfig } from "payload";
import { sqliteAdapter } from "@payloadcms/db-sqlite";
import { lexicalEditor } from "@payloadcms/richtext-lexical";
import { seoPlugin } from "@payloadcms/plugin-seo";
import sharp from "sharp";

import { Posts } from "./collections/Posts";
import { Categories } from "./collections/Categories";
import { Media } from "./collections/Media";
import { Submissions } from "./collections/Submissions";
import { Users } from "./collections/Users";
import { NotificationSettings } from "./globals/NotificationSettings";
// Generated by `npx payload migrate:create`. In production the SQLite adapter
// auto-applies these during connect() (before onInit), so a fresh disk gets
// its schema without a manual migrate step. Keep `push: true` for dev only.
import { migrations } from "./migrations";

const dirname = path.dirname(fileURLToPath(import.meta.url));

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000";
// Allow admin/API auth from both the canonical domain and Render's own URL
// (RENDER_EXTERNAL_URL is auto-set), so /admin works on ias-website.onrender.com
// before the domain is cut over, and on iasamerica.com after.
const allowedOrigins = [siteUrl, process.env.RENDER_EXTERNAL_URL].filter(
  (v): v is string => Boolean(v),
);

export default buildConfig({
  admin: {
    user: Users.slug,
    meta: {
      titleSuffix: " · IAS Science Hub",
      description: "Content management for the IAS Science Hub.",
    },
    components: {
      // On-brand admin login/nav graphics (IAS logo). Registered via importMap.
      graphics: {
        Logo: "/components/admin/Logo#Logo",
        Icon: "/components/admin/Icon#Icon",
      },
      // Cloudflare Turnstile bot-gate above the login form (no-op until keys set).
      beforeLogin: ["/components/admin/TurnstileGate#TurnstileGate"],
    },
    // Resolve component string paths (above) relative to /src.
    importMap: { baseDir: dirname },
  },
  collections: [Posts, Categories, Media, Submissions, Users],
  globals: [NotificationSettings],
  editor: lexicalEditor(),
  secret: process.env.PAYLOAD_SECRET || "",
  // Seed the first admin from secret env vars the first time the app boots
  // on an empty database. This eliminates the public "create first user" race:
  // by the time the server responds to /admin, an admin already exists, so the
  // unauthenticated create-user form is never served. Idempotent — once a user
  // exists this does nothing, even if the env vars remain. Rotate the password
  // in /admin after first login, then unset the SEED_ADMIN_* vars.
  onInit: async (payload) => {
    // In production the SQLite adapter auto-runs migrations during connect()
    // (before onInit), so the users table exists by here. During `migrate:create`
    // or if migrations haven't applied yet, the table may be absent — count would
    // throw. Swallow that specific case (and warn) rather than crash app boot.
    let totalDocs = 0;
    try {
      ({ totalDocs } = await payload.count({ collection: "users" }));
    } catch {
      payload.logger.warn(
        "onInit admin-seed skipped: users table not present yet (migrations pending). " +
          "It will seed on the next boot once migrations have applied.",
      );
      return;
    }
    if (totalDocs > 0) return;
    const email = process.env.SEED_ADMIN_EMAIL?.trim();
    const password = process.env.SEED_ADMIN_PASSWORD;
    if (!email || !password) {
      payload.logger.warn(
        "Users collection is empty and SEED_ADMIN_EMAIL/SEED_ADMIN_PASSWORD are not set — " +
          "the public /admin create-first-user screen will be exposed until an admin is created.",
      );
      return;
    }
    await payload.create({
      collection: "users",
      data: {
        email,
        name: process.env.SEED_ADMIN_NAME?.trim() || "Admin",
        roles: ["admin"],
        password,
      },
    });
    payload.logger.info(`Seeded first admin user from env: ${email}`);
  },
  db: sqliteAdapter({
    client: { url: process.env.DATABASE_URI || "file:./blog.db" },
    // Auto-sync schema on boot in DEV only (the adapter gates push to
    // non-production). In production, `prodMigrations` are applied during
    // connect() instead — so a fresh Render disk gets its tables on first boot
    // without a manual migrate step. For schema changes, generate a new
    // migration (`npm run payload -- migrate:create`) and commit it.
    push: true,
    prodMigrations: migrations,
  }),
  sharp,
  cors: allowedOrigins,
  csrf: allowedOrigins,
  typescript: { outputFile: path.resolve(dirname, "payload-types.ts") },
  plugins: [
    seoPlugin({
      collections: ["posts"],
      uploadsCollection: "media",
      tabbedUI: true,
      generateTitle: ({ doc }: { doc?: { title?: string } }) =>
        doc?.title ? `${doc.title} | IAS Science Hub` : "IAS Science Hub",
      generateDescription: ({ doc }: { doc?: { excerpt?: string } }) => doc?.excerpt ?? "",
    }),
  ],
});
